// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAFhLV_79Yj04f2O40-ZJvv2VIXecPTkhQ',
    appId: '1:210633721860:web:6be2b7eb5677741d814d51',
    messagingSenderId: '210633721860',
    projectId: 'sentri-zk-chat',
    authDomain: 'sentri-zk-chat.firebaseapp.com',
    storageBucket: 'sentri-zk-chat.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCIea0xd1BUggm1GLtVl3R2wYqmdWnrq_E',
    appId: '1:210633721860:android:9191c905441beff0814d51',
    messagingSenderId: '210633721860',
    projectId: 'sentri-zk-chat',
    storageBucket: 'sentri-zk-chat.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBAcG8xv5EnxyiKcJUdX29G9LWmBzNpsDM',
    appId: '1:210633721860:ios:e2ecd229f9ee5303814d51',
    messagingSenderId: '210633721860',
    projectId: 'sentri-zk-chat',
    storageBucket: 'sentri-zk-chat.firebasestorage.app',
    iosBundleId: 'com.example.mobile',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBAcG8xv5EnxyiKcJUdX29G9LWmBzNpsDM',
    appId: '1:210633721860:ios:e2ecd229f9ee5303814d51',
    messagingSenderId: '210633721860',
    projectId: 'sentri-zk-chat',
    storageBucket: 'sentri-zk-chat.firebasestorage.app',
    iosBundleId: 'com.example.mobile',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAFhLV_79Yj04f2O40-ZJvv2VIXecPTkhQ',
    appId: '1:210633721860:web:5c3471f4cf54a0be814d51',
    messagingSenderId: '210633721860',
    projectId: 'sentri-zk-chat',
    authDomain: 'sentri-zk-chat.firebaseapp.com',
    storageBucket: 'sentri-zk-chat.firebasestorage.app',
  );
}
